/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PostEditLazyImport = createFileRoute('/postEdit')()
const PostLazyImport = createFileRoute('/post')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PostEditLazyRoute = PostEditLazyImport.update({
  path: '/postEdit',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/postEdit.lazy').then((d) => d.Route))

const PostLazyRoute = PostLazyImport.update({
  path: '/post',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/post.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostLazyImport
      parentRoute: typeof rootRoute
    }
    '/postEdit': {
      id: '/postEdit'
      path: '/postEdit'
      fullPath: '/postEdit'
      preLoaderRoute: typeof PostEditLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  PostLazyRoute,
  PostEditLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/post",
        "/postEdit"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/post": {
      "filePath": "post.lazy.tsx"
    },
    "/postEdit": {
      "filePath": "postEdit.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
